kafka.aggregator.bootstrap-servers=localhost:9092
kafka.aggregator.sensor-event-topic=telemetry.sensors.v1
kafka.aggregator.snapshot-topic=telemetry.snapshots.v1

kafka.aggregator.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.aggregator.consumer.value-deserializer=ru.yandex.practicum.kafka.telemetry.serializer.SensorEventAvroDeserializer
kafka.aggregator.consumer.group-id=aggregator
kafka.aggregator.consumer.client-id=consumer1

kafka.aggregator.consumer.properties.fetch-min-bytes=100
kafka.aggregator.consumer.properties.enable-auto-commit=false
kafka.aggregator.consumer.properties.fetch-max-wait-ms=10000
kafka.aggregator.consumer.properties.max-partition-fetch-bytes=1000000
kafka.aggregator.consumer.properties.max-poll-records=10

kafka.aggregator.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.aggregator.producer.value-serializer=ru.yandex.practicum.kafka.telemetry.serializer.GeneralAvroSerializer