spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
#spring.jpa.show-sql=true
#---
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=dbuser
spring.datasource.password=12345
#---
kafka.analyzer.bootstrap-servers=localhost:9092
kafka.analyzer.hubs-event-topic=telemetry.hubs.v1
kafka.analyzer.snapshots-topic=telemetry.snapshots.v1
#---
kafka.analyzer.hub-consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.analyzer.hub-consumer.value-deserializer=ru.yandex.practicum.kafka.telemetry.serializer.HubEventAvroDeserializer
kafka.analyzer.hub-consumer.group-id=analyzer
kafka.analyzer.hub-consumer.client-id=hub-consumer1
kafka.analyzer.hub-consumer.properties.fetch-min-bytes=100
kafka.analyzer.hub-consumer.properties.enable-auto-commit=false
kafka.analyzer.hub-consumer.properties.fetch-max-wait-ms=10000
kafka.analyzer.hub-consumer.properties.max-partition-fetch-bytes=1000000
kafka.analyzer.hub-consumer.properties.max-poll-records=10
#---
kafka.analyzer.snapshot-consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.analyzer.snapshot-consumer.value-deserializer=ru.yandex.practicum.kafka.telemetry.serializer.SensorsSnapshotAvroDeserializer
kafka.analyzer.snapshot-consumer.group-id=analyzer
kafka.analyzer.snapshot-consumer.client-id=snapshot-consumer1
kafka.analyzer.snapshot-consumer.properties.fetch-min-bytes=100
kafka.analyzer.snapshot-consumer.properties.enable-auto-commit=false
kafka.analyzer.snapshot-consumer.properties.fetch-max-wait-ms=10000
kafka.analyzer.snapshot-consumer.properties.max-partition-fetch-bytes=1000000
kafka.analyzer.snapshot-consumer.properties.max-poll-records=10
#---
grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enable-keep-alive=true
grpc.client.hub-router.keep-alive-without-calls=true
grpc.client.hub-router.negotiation-type=plaintext