kafka:
  collector:
    bootstrap-servers: localhost:9092
    sensor-event-topic: telemetry.sensors.v1
    hub-event-topic: telemetry.hubs.v1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka.telemetry.serializer.GeneralAvroSerializer

grpc:
  server:
    port: 59091
