CREATE TABLE IF NOT EXISTS dimensions
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    width  NUMERIC(100, 2) NOT NULL,
    height NUMERIC(100, 2) NOT NULL,
    depth  NUMERIC(100, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS warehouse
(
    product_id   UUID,
    dimension_id BIGINT REFERENCES dimensions (id) ON DELETE CASCADE,
    weight       NUMERIC(100, 2) NOT NULL,
    fragile      BOOLEAN,
    quantity     BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

